# Generated by Django 6.0.5 on 2026-05-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAuth2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfachallenge',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
